pipeline {                                                                                                                                                                                                       
      agent any                                                                                                                                                                                                    
                                                                                                                                                                                                                   
      environment {                                                                                                                                                                                                
          LOCAL_REGISTRY = 'localhost:5000'                                                                                                                                                                        
          OPENCHOREO_API_URL = 'http://api.openchoreo.localhost:8080/api/v1'                                                                                                                                       
          IMAGE = "${LOCAL_REGISTRY}/greeting-service:${BUILD_NUMBER}"                                                                                                                                             
      }                                                                                                                                                                                                            
                                                                                                                                                                                                                   
      stages {                                                                                                                                                                                                     
          stage('Build') {                                                                                                                                                                                         
              steps {                                                                                                                                                                                              
                  dir('service-go-greeter') {                                                                                                                                                                      
                      sh 'docker build -t ${IMAGE} -f Dockerfile .'                                                                                                                                                
                  }                                                                                                                                                                                                
              }                                                                                                                                                                                                    
          }                                                                                                                                                                                                        
                                                                                                                                                                                                                   
          stage('Push') {                                                                                                                                                                                          
              steps {                                                                                                                                                                                              
                  sh 'docker push ${IMAGE}'                                                                                                                                                                        
              }                                                                                                                                                                                                    
          }                                                                                                                                                                                                        
                                                                                                                                                                                                                   
          stage('Deploy') {                                                                                                                                                                                        
              steps {                                                                                                                                                                                              
                  withCredentials([string(credentialsId: 'openchoreo-token', variable: 'TOKEN')]) {                                                                                                                
                      sh '''                                                                                                                                                                                       
                          curl -X POST "${OPENCHOREO_API_URL}/namespaces/default/projects/default/components/greeting-service/workloads" \                                                                         
                              -H "Content-Type: application/json" \                                                                                                                                                
                              -H "Authorization: Bearer ${TOKEN}" \                                                                                                                                                
                              -d '{"containers":{"main":{"image":"'"${IMAGE}"'"}}}'                                                                                                                                
                      '''                                                                                                                                                                                          
                  }                                                                                                                                                                                                
              }                                                                                                                                                                                                    
          }                                                                                                                                                                                                        
      }                                                                                                                                                                                                            
  }
